stages:
#  - compile
#  - test
  - backend

#compile:
#  stage: compile
#  script:
#    - ./gradlew assemble

#test-syntax:
#  stage: test
#  script:
#    - ./gradlew test -i -Dtest.type=syntax
#  artifacts:
#    when: always
#    reports:
#      junit: build/test-results/test/**/TEST-*.xml
#
#test-semantic:
#  stage: test
#  script:
#    - ./gradlew test -i -Dtest.type=semantic
#  artifacts:
#    when: always
#    reports:
#      junit: build/test-results/test/**/TEST-*.xml
#
#test-valid:
#  stage: test
#  script:
#    - ./gradlew test -i -Dtest.type=valid
#  artifacts:
#    when: always
#    reports:
#      junit: build/test-results/test/**/TEST-*.xml

test-backend:
  stage: backend
  script:
    - apt-get install libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev build-essential bison flex libssl-dev bc
    - apt-get install gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
    - ./gradlew test -i -Dtest.type=backend