image: gradle:4.7.0-jdk8-alpine

stages:
  - compile
  - test
  - deploy

compile:
  stage: compile
  script:
    - ./gradlew generateGrammarSource
    - ./gradlew shadowJar

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - echo "Finished running compile scripts & tests"