image: java:8-jdk

stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test -i
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml